services:
  qdrant:
    image: 'qdrant/qdrant:latest'
    ports:
      - '6334:6334'

  mongodb:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: